// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoqhUGfD7eS_59-4YOnYS4D95Rj7tRdu4',
    appId: '1:748963403939:web:b85954ebc8cd15601fc716',
    messagingSenderId: '748963403939',
    projectId: 'laqahy',
    authDomain: 'laqahy.firebaseapp.com',
    storageBucket: 'laqahy.appspot.com',
    measurementId: 'G-YN4WNL9L01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSdBdWPYmB2KaUxpZpQQD-2WLJTva7QIc',
    appId: '1:748963403939:android:295c8a251c4f0b631fc716',
    messagingSenderId: '748963403939',
    projectId: 'laqahy',
    storageBucket: 'laqahy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2y5aZHYfIirrEj-fUjKJW2SwWyLVeJxs',
    appId: '1:748963403939:ios:fe9510dadf1bdaf11fc716',
    messagingSenderId: '748963403939',
    projectId: 'laqahy',
    storageBucket: 'laqahy.appspot.com',
    iosBundleId: 'com.sourcetech.laqahy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2y5aZHYfIirrEj-fUjKJW2SwWyLVeJxs',
    appId: '1:748963403939:ios:fe9510dadf1bdaf11fc716',
    messagingSenderId: '748963403939',
    projectId: 'laqahy',
    storageBucket: 'laqahy.appspot.com',
    iosBundleId: 'com.sourcetech.laqahy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoqhUGfD7eS_59-4YOnYS4D95Rj7tRdu4',
    appId: '1:748963403939:web:eb5f3f6b5540edf81fc716',
    messagingSenderId: '748963403939',
    projectId: 'laqahy',
    authDomain: 'laqahy.firebaseapp.com',
    storageBucket: 'laqahy.appspot.com',
    measurementId: 'G-5N379SP3S8',
  );
}
